### ISSUE TITLE
Cornerstone3D not work

### ISSUE THREAD

**Issue by acegank** [cornerstonejs/cornerstone-nifti-image-loader#49] opened 2022-10-09 14:09 UTC
`
import * as cornerstone from "@cornerstonejs/core/dist/esm";
`
`
import * as cornerstoneNIFTIImageLoader from "@cornerstonejs/nifti-image-loader/dist/cornerstoneNIFTIImageLoader";
`
`
cornerstoneNIFTIImageLoader.external.cornerstone = cornerstone;
`

but will error:

`
 Cannot read properties of undefined (reading 'dispatchEvent')
`
Cornerstone3D has not **events** properties

how to solve this？

**Comment by kousu** [comment] 2022-10-09 17:02
The maintainer [explained yesterday](https://github.com/cornerstonejs/cornerstone-nifti-image-loader/issues/48#issuecomment-1271794397) that unfortunately they are not yet compatible. So you cannot use

```
npm install @cornerstonejs/core   # aka "Cornerstone3D"
npm install @cornerstonejs/nifti-image-loader
```

You have to instead use

```
npm install cornerstone-core # aka "legacy Cornerstone"
npm install @cornerstonejs/nifti-image-loader  # gets 1.0.7 of this project
```

or


```
npm install cornerstone-core
npm install cornerstonejs-nifti-image-loader  # which gets the older 1.0.0 of this project
```

Not even the [OHIF viewer](https://viewer.ohif.org/), which is the main consumer and funder of Cornerstone, uses Cornerstone3D yet:

https://github.com/OHIF/Viewers/blob/7aba01f534b70406ce02e1708004141c7b773904/extensions/cornerstone/package.json#L35-L38

**Comment by kousu** [comment] 2022-10-09 19:14
@acegank, if it helps, I've [rewritten the example](https://gist.github.com/kousu/2a31328d9c320393fbd603534265faa7), that uses the latest nifti loader with the latest `cornerstone-core`: 

![screenshot](https://gist.githubusercontent.com/kousu/2a31328d9c320393fbd603534265faa7/raw/b0c639ea55199ed882f9037d8293cef265a60aa5/screenshot.png)

Unlike the older examples, my rewrite uses the Cornerstone directly off npm, instead using an old vendored copy, but it doesn't go as far as upgrading all the way to Cornerstone3D because that's impossible at the moment.

You'll have to adapt the packaging to your project, whether you're using webpack or node or rollup, and you'll probably want to add `cornerstone-tools` to make it more useful, but it successfully displays a .nii.gz file and should get you going.

Would you consider closing this issue now? I think it's fair to say this is a duplicate of my post at #48.

**Comment by acegank** [comment] 2022-10-10 01:39
@kousu ，Thank you for the clarification! 

I have another question for you, there are two nifti files， one is origin files, one is mask files(segmentation), how to overlay them？

Thanks you again!

**Closed** 2022-10-10 01:39 UTC

**Comment by kousu** [comment] 2022-10-10 05:54
> I have another question for you, there are two nifti files， one is origin files, one is mask files(segmentation), how to overlay them？

That's a good question. I hadn't thought of trying to do that, but knowing how to do layers would be good. I have no idea. I don't even know.

The reason I posted #48 is because I am also a newbie to Cornerstone and I got lost in the documentation's sprawl, and it's apparently currently worse because they're going through a major version upgrade.

I took a look through the docs and found [this](https://www.cornerstonejs.org/docs/concepts/cornerstone-tools/segmentation/segmentation-display), but I can't really tell if that will do the right thing, or if it's even the right code because, again, that's from the Cornerstone3D docs. But maybe if you combine reading that with reading the source of [`cornerstone-tools`](https://www.npmjs.com/package/cornerstone-tools) you can get it to work.

Anyway that's about all I have time for right now, but good luck with your project!

**Comment by acegank** [comment] 2022-10-10 09:26
thanks! you are right. if use Cornerstone3D  will be easy. but use cornerstone-core i can't solve it. 

i try many times，but..😔

anyway, thank you.

**Comment by x6262** [comment] 2023-05-21 05:24
Have you solved the problem of compatibility between cornerstone3D and nifti files yet?
